import type { FeatureDescriptor, FeatureMatcher, FeatureSet, Keypoint } from "./features";
import type { ScanFrame } from "./live-scan";

export interface VisionExtractor { extract(frame: ScanFrame): Promise<FeatureSet>; }
export interface DescriptorMatcher extends FeatureMatcher {}
export interface LocalVisionOptions { readonly maxKeypoints?: number; readonly patchRadius?: number; readonly minScore?: number; }

export class LocalVisionExtractor implements VisionExtractor {
  private readonly maxKeypoints: number;
  private readonly patchRadius: number;
  private readonly minScore: number;
  constructor(options: LocalVisionOptions = {}) { this.maxKeypoints = Math.max(16, Math.min(2048, options.maxKeypoints ?? 512)); this.patchRadius = Math.max(1, Math.min(4, options.patchRadius ?? 2)); this.minScore = Math.max(0, Math.min(1, options.minScore ?? 0.12)); }
  async extract(frame: ScanFrame): Promise<FeatureSet> { const { data, width, height } = frame.image; const candidates: Keypoint[] = []; const step = Math.max(2, Math.floor(Math.min(width, height) / 160)); for (let y = this.patchRadius + 1; y < height - this.patchRadius - 1; y += step) for (let x = this.patchRadius + 1; x < width - this.patchRadius - 1; x += step) { const gx = luminance(data, width, x + 1, y) - luminance(data, width, x - 1, y); const gy = luminance(data, width, x, y + 1) - luminance(data, width, x, y - 1); const score = Math.min(1, Math.hypot(gx, gy) / 255); if (score >= this.minScore) candidates.push({ x, y, score }); } candidates.sort((a, b) => b.score - a.score); const keypoints = suppressNearby(candidates, this.maxKeypoints, Math.max(3, step * 2)); return { keypoints, descriptors: keypoints.map((point) => ({ values: descriptor(data, width, height, point, this.patchRadius), dimension: (this.patchRadius * 2 + 1) ** 2 })) }; }
}
export class BruteForceDescriptorMatcher implements DescriptorMatcher { constructor(private readonly ratio = 0.8) {} match(reference: FeatureSet, current: FeatureSet) { const matches: { referenceIndex: number; currentIndex: number; distance: number }[] = []; for (let i = 0; i < reference.descriptors.length; i++) { const a = reference.descriptors[i]; if (!a) continue; let best = Number.POSITIVE_INFINITY, second = Number.POSITIVE_INFINITY, bestIndex = -1; for (let j = 0; j < current.descriptors.length; j++) { const b = current.descriptors[j]; if (!b || b.dimension !== a.dimension) continue; const distance = l2(a.values, b.values); if (distance < best) { second = best; best = distance; bestIndex = j; } else if (distance < second) second = distance; } if (bestIndex >= 0 && best <= second * this.ratio) matches.push({ referenceIndex: i, currentIndex: bestIndex, distance: best }); } return matches; } }
function luminance(data: Uint8ClampedArray, width: number, x: number, y: number): number { const i = (y * width + x) * 4; return 0.2126 * data[i]! + 0.7152 * data[i + 1]! + 0.0722 * data[i + 2]!; }
function descriptor(data: Uint8ClampedArray, width: number, height: number, point: Keypoint, radius: number): Float32Array { const size = radius * 2 + 1, values = new Float32Array(size * size); let k = 0, sum = 0; for (let dy = -radius; dy <= radius; dy++) for (let dx = -radius; dx <= radius; dx++) { const x = Math.max(0, Math.min(width - 1, Math.round(point.x + dx))); const y = Math.max(0, Math.min(height - 1, Math.round(point.y + dy))); const value = luminance(data, width, x, y) / 255; values[k++] = value; sum += value; } const mean = sum / values.length; let norm = 0; for (let i = 0; i < values.length; i++) { values[i] -= mean; norm += values[i]! * values[i]!; } norm = Math.sqrt(norm) || 1; for (let i = 0; i < values.length; i++) values[i] /= norm; return values; }
function l2(a: Float32Array, b: Float32Array): number { let sum = 0; for (let i = 0; i < a.length; i++) { const d = a[i]! - b[i]!; sum += d * d; } return Math.sqrt(sum); }
function suppressNearby(points: readonly Keypoint[], max: number, radius: number): Keypoint[] { const selected: Keypoint[] = [], r2 = radius * radius; for (const point of points) { if (selected.every((other) => (other.x - point.x) ** 2 + (other.y - point.y) ** 2 >= r2)) selected.push(point); if (selected.length >= max) break; } return selected; }
