//! Typed WASM boundary between the Rust engine and the TypeScript Studio.
//!
//! This crate is intentionally thin: it re-exports domain types from
//! `veylune-core`, `veylune-geometry`, and `veylune-reconstruction` through
//! `wasm-bindgen`, and is the single place `unsafe` (generated by
//! `wasm-bindgen`) is allowed in the workspace. No reconstruction algorithms
//! live here — see ADR-013 and `docs/75-production-task-pipeline.md` Stage 1
//! for the migration that will make this crate the load-bearing bridge for
//! the ported bundle-adjustment/triangulation/SE3 pipeline.

use veylune_core::{Confidence, EvidenceState, PROJECT_SCHEMA_VERSION};
use veylune_reconstruction::{ReconstructionProgress, ReconstructionStage};
use veylune_runtime::{CapabilityProfile, ExecutionBackend, QualityTier};
use wasm_bindgen::prelude::*;

/// The engine's semantic version, exposed so the TS shell can assert
/// compatibility with the WASM binary it loaded.
#[wasm_bindgen]
pub fn engine_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// The project schema version this engine build supports, so the TS project
/// service can detect a mismatch before attempting to load a project.
#[wasm_bindgen]
pub fn project_schema_version() -> u32 {
    PROJECT_SCHEMA_VERSION
}

/// Mirrors [`veylune_runtime::CapabilityProfile`] across the WASM boundary.
#[wasm_bindgen(getter_with_clone)]
pub struct WasmCapabilityProfile {
    pub webgpu: bool,
    pub wasm_simd: bool,
    pub wasm_threads: bool,
    pub quality: WasmQualityTier,
}

#[wasm_bindgen]
#[derive(Clone, Copy)]
pub enum WasmQualityTier {
    Preview,
    Balanced,
    High,
    Maximum,
}

impl From<QualityTier> for WasmQualityTier {
    fn from(tier: QualityTier) -> Self {
        match tier {
            QualityTier::Preview => WasmQualityTier::Preview,
            QualityTier::Balanced => WasmQualityTier::Balanced,
            QualityTier::High => WasmQualityTier::High,
            QualityTier::Maximum => WasmQualityTier::Maximum,
        }
    }
}

impl From<WasmQualityTier> for QualityTier {
    fn from(tier: WasmQualityTier) -> Self {
        match tier {
            WasmQualityTier::Preview => QualityTier::Preview,
            WasmQualityTier::Balanced => QualityTier::Balanced,
            WasmQualityTier::High => QualityTier::High,
            WasmQualityTier::Maximum => QualityTier::Maximum,
        }
    }
}

#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WasmExecutionBackend {
    WebGpu,
    Wasm,
    Native,
}

impl From<ExecutionBackend> for WasmExecutionBackend {
    fn from(backend: ExecutionBackend) -> Self {
        match backend {
            ExecutionBackend::WebGpu => WasmExecutionBackend::WebGpu,
            ExecutionBackend::Wasm => WasmExecutionBackend::Wasm,
            ExecutionBackend::Native => WasmExecutionBackend::Native,
        }
    }
}

/// Runs the same backend-selection logic the Rust runtime uses natively,
/// so browser capability detection and native tooling never disagree.
#[wasm_bindgen]
pub fn preferred_backend(
    webgpu: bool,
    wasm_simd: bool,
    wasm_threads: bool,
    quality: WasmQualityTier,
) -> WasmExecutionBackend {
    let profile = CapabilityProfile {
        webgpu,
        wasm_simd,
        wasm_threads,
        quality: quality.into(),
    };
    profile.preferred_backend().into()
}

/// Clamps confidence components into `[0, 1]`, exposed so the TS viewer and
/// the Rust engine apply exactly the same rule.
#[wasm_bindgen]
pub fn clamp_confidence(geometry: f32, texture: f32, pose: f32, detail: f32) -> Vec<f32> {
    let clamped = Confidence {
        geometry,
        texture,
        pose,
        detail,
    }
    .clamped();
    vec![
        clamped.geometry,
        clamped.texture,
        clamped.pose,
        clamped.detail,
    ]
}

#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WasmEvidenceState {
    Observed,
    Reconstructed,
    Inferred,
    Generated,
    Uncertain,
    Unavailable,
}

impl From<EvidenceState> for WasmEvidenceState {
    fn from(state: EvidenceState) -> Self {
        match state {
            EvidenceState::Observed => WasmEvidenceState::Observed,
            EvidenceState::Reconstructed => WasmEvidenceState::Reconstructed,
            EvidenceState::Inferred => WasmEvidenceState::Inferred,
            EvidenceState::Generated => WasmEvidenceState::Generated,
            EvidenceState::Uncertain => WasmEvidenceState::Uncertain,
            EvidenceState::Unavailable => WasmEvidenceState::Unavailable,
        }
    }
}

#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WasmReconstructionStage {
    Analysis,
    CoarseShape,
    Surface,
    Texture,
    Optimization,
    Ready,
}

impl From<ReconstructionStage> for WasmReconstructionStage {
    fn from(stage: ReconstructionStage) -> Self {
        match stage {
            ReconstructionStage::Analysis => WasmReconstructionStage::Analysis,
            ReconstructionStage::CoarseShape => WasmReconstructionStage::CoarseShape,
            ReconstructionStage::Surface => WasmReconstructionStage::Surface,
            ReconstructionStage::Texture => WasmReconstructionStage::Texture,
            ReconstructionStage::Optimization => WasmReconstructionStage::Optimization,
            ReconstructionStage::Ready => WasmReconstructionStage::Ready,
        }
    }
}

/// Computes reconstruction progress fraction using the same
/// [`ReconstructionProgress`] logic the native engine uses.
#[wasm_bindgen]
pub fn reconstruction_progress_fraction(completed_steps: u32, total_steps: u32) -> f32 {
    ReconstructionProgress {
        stage: ReconstructionStage::Analysis,
        completed_steps,
        total_steps,
    }
    .fraction()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn engine_version_is_semver_shaped() {
        assert!(engine_version().split('.').count() >= 2);
    }

    #[test]
    fn preferred_backend_prefers_webgpu_when_available() {
        assert_eq!(
            preferred_backend(true, false, false, WasmQualityTier::Balanced),
            WasmExecutionBackend::WebGpu
        );
        assert_eq!(
            preferred_backend(false, false, false, WasmQualityTier::Balanced),
            WasmExecutionBackend::Wasm
        );
    }

    #[test]
    fn clamp_confidence_clamps_out_of_range_inputs() {
        let clamped = clamp_confidence(-1.0, 0.5, 2.0, 0.25);
        assert_eq!(clamped, vec![0.0, 0.5, 1.0, 0.25]);
    }

    #[test]
    fn reconstruction_progress_fraction_matches_native_logic() {
        assert_eq!(reconstruction_progress_fraction(5, 10), 0.5);
        assert_eq!(reconstruction_progress_fraction(0, 0), 0.0);
    }
}
