import { describe, expect, it } from "vitest";
import { WorkerJobTransport } from "./worker-transport";
class FakeWorker { readonly messages: unknown[] = []; private messageListeners: ((event: MessageEvent) => void)[] = []; private errorListeners: ((event: ErrorEvent) => void)[] = []; terminated = false; postMessage(message: unknown): void { this.messages.push(message); } addEventListener(type: "message", listener: (event: MessageEvent) => void): void; addEventListener(type: "error", listener: (event: ErrorEvent) => void): void; addEventListener(type: "message" | "error", listener: ((event: MessageEvent) => void) | ((event: ErrorEvent) => void)): void { if (type === "message") this.messageListeners.push(listener as (event: MessageEvent) => void); else this.errorListeners.push(listener as (event: ErrorEvent) => void); } removeEventListener(type: "message", listener: (event: MessageEvent) => void): void; removeEventListener(type: "error", listener: (event: ErrorEvent) => void): void; removeEventListener(type: "message" | "error", listener: (event: ErrorEvent) => void): void; removeEventListener(type: "message" | "error", listener: ((event: MessageEvent) => void) | ((event: ErrorEvent) => void)): void { if (type === "message") this.messageListeners = this.messageListeners.filter((candidate) => candidate !== listener); else this.errorListeners = this.errorListeners.filter((candidate) => candidate !== listener); } terminate(): void { this.terminated = true; } emit(message: unknown): void { for (const listener of this.messageListeners) listener({ data: message } as MessageEvent); } emitError(message = "boom"): void { for (const listener of this.errorListeners) listener({ message } as ErrorEvent); } }

describe("WorkerJobTransport", () => {
  it("submits, forwards events, cancels and disposes", async () => { const worker = new FakeWorker(); const transport = new WorkerJobTransport<{ value: number }, number>(worker); const events: unknown[] = []; transport.subscribe((event) => events.push(event)); await transport.submit({ id: "job-1", operation: "test", input: { value: 1 } }); worker.emit({ type: "progress", status: { id: "job-1", state: "running", progress: { completed: 1, total: 2 } } }); expect(events).toHaveLength(1); await transport.cancel("job-1"); expect(worker.messages.at(-1)).toEqual({ type: "cancel", id: "job-1" }); expect((events.at(-1) as { status: { state: string } }).status.state).toBe("cancelled"); worker.emit({ type: "completed", status: { id: "job-1", state: "completed", progress: { completed: 1, total: 1 } }, output: 1 }); expect(events).toHaveLength(2); transport.dispose(); expect(worker.terminated).toBe(true); });
  it("rejects duplicate jobs and ignores stale or malformed messages", async () => { const worker = new FakeWorker(); const transport = new WorkerJobTransport<void, number>(worker); const events: unknown[] = []; transport.subscribe((event) => events.push(event)); await transport.submit({ id: "job-1", operation: "test", input: undefined }); await expect(transport.submit({ id: "job-1", operation: "test", input: undefined })).rejects.toThrow(); worker.emit({ type: "completed", status: { id: "unknown", state: "completed", progress: { completed: 1, total: 1 } }, output: 1 }); worker.emit({ nope: true }); expect(events).toHaveLength(0); });
  it("fails all active jobs on worker failure", async () => { const worker = new FakeWorker(); const transport = new WorkerJobTransport<void, number>(worker); const events: unknown[] = []; transport.subscribe((event) => events.push(event)); await transport.submit({ id: "job-1", operation: "test", input: undefined }); await transport.submit({ id: "job-2", operation: "test", input: undefined }); worker.emitError("crashed"); expect(events).toHaveLength(2); expect((events[0] as { status: { state: string } }).status.state).toBe("failed"); });
});
