import type { ArtifactRecord, ProjectRevision, ProjectStore, StudioProjectRecord, StoredArtifactData } from "./contracts";

const DATABASE_VERSION = 3;
const ARTIFACTS = "artifacts";
const REVISIONS = "revisions";
const RECONSTRUCTION_SESSIONS = "reconstructionSessions";
const STUDIO_PROJECTS = "studioProjects";
interface StoredArtifact extends ArtifactRecord { data: ArrayBuffer }

export class IndexedDbProjectStore implements ProjectStore {
  constructor(private readonly databaseName = "veylune") {}
  async readRevision(projectId: string): Promise<ProjectRevision | undefined> { assertProjectId(projectId); const db = await openDatabase(this.databaseName); try { return await requestValue<ProjectRevision | undefined>(db.transaction(REVISIONS, "readonly").objectStore(REVISIONS).get(projectId)); } finally { db.close(); } }
  async stageArtifact(record: ArtifactRecord, data: ArrayBuffer): Promise<void> { validateArtifact(record, data); const actualHash = await sha256Hex(data); if (actualHash !== record.hash) throw new Error("Artifact hash does not match content."); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(ARTIFACTS, "readwrite"); transaction.objectStore(ARTIFACTS).put({ ...record, data } satisfies StoredArtifact); await transactionComplete(transaction); } finally { db.close(); } }
  async commitRevision(revision: ProjectRevision): Promise<void> { validateRevision(revision); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(REVISIONS, "readwrite"); const store = transaction.objectStore(REVISIONS); const current = await requestValue<ProjectRevision | undefined>(store.get(revision.projectId)); if (current && (revision.parentRevision === undefined || revision.parentRevision !== current.revision)) { transaction.abort(); throw new Error("Revision conflict: parent revision is stale."); } if (!current && revision.parentRevision !== undefined) { transaction.abort(); throw new Error("Revision conflict: project does not exist."); } if (current && revision.revision !== current.revision + 1) { transaction.abort(); throw new Error("Revision numbers must increase monotonically."); } store.put(revision); await transactionComplete(transaction); } finally { db.close(); } }
  async deleteProject(projectId: string): Promise<void> { assertProjectId(projectId); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction([REVISIONS, STUDIO_PROJECTS, ARTIFACTS, RECONSTRUCTION_SESSIONS], "readwrite"); const revisions = transaction.objectStore(REVISIONS); const projects = transaction.objectStore(STUDIO_PROJECTS); const [revision, project] = await Promise.all([requestValue<ProjectRevision | undefined>(revisions.get(projectId)), requestValue<StudioProjectRecord | undefined>(projects.get(projectId))]); for (const id of new Set([...(revision?.artifactIds ?? []), ...(project?.assetIds ?? [])])) transaction.objectStore(ARTIFACTS).delete(id); revisions.delete(projectId); projects.delete(projectId); transaction.objectStore(RECONSTRUCTION_SESSIONS).delete(projectId); await transactionComplete(transaction); } finally { db.close(); } }
  async listProjects(): Promise<readonly StudioProjectRecord[]> { const db = await openDatabase(this.databaseName); try { const values = await requestValue<StudioProjectRecord[]>(db.transaction(STUDIO_PROJECTS, "readonly").objectStore(STUDIO_PROJECTS).getAll()); return values.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); } finally { db.close(); } }
  async writeProjectMetadata(project: StudioProjectRecord): Promise<void> { validateProjectMetadata(project); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(STUDIO_PROJECTS, "readwrite"); transaction.objectStore(STUDIO_PROJECTS).put(project); await transactionComplete(transaction); } finally { db.close(); } }
  async readArtifacts(artifactIds: readonly string[]): Promise<readonly StoredArtifactData[]> { const db = await openDatabase(this.databaseName); try { const store = db.transaction(ARTIFACTS, "readonly").objectStore(ARTIFACTS); const values = await Promise.all(artifactIds.map((id) => requestValue<StoredArtifact | undefined>(store.get(id)))); return values.filter((value): value is StoredArtifact => value !== undefined).map(({ data, ...record }) => ({ record, data })); } finally { db.close(); } }
  async deleteArtifacts(artifactIds: readonly string[]): Promise<void> { if (!artifactIds.length) return; const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(ARTIFACTS, "readwrite"); const store = transaction.objectStore(ARTIFACTS); for (const id of artifactIds) store.delete(id); await transactionComplete(transaction); } finally { db.close(); } }
  async readReconstructionSession(projectId: string): Promise<unknown | undefined> { assertProjectId(projectId); const db = await openDatabase(this.databaseName); try { return await requestValue<unknown | undefined>(db.transaction(RECONSTRUCTION_SESSIONS, "readonly").objectStore(RECONSTRUCTION_SESSIONS).get(projectId)); } finally { db.close(); } }
  async writeReconstructionSession(projectId: string, session: unknown): Promise<void> { assertProjectId(projectId); if (!session || typeof session !== "object") throw new Error("Invalid reconstruction session."); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(RECONSTRUCTION_SESSIONS, "readwrite"); transaction.objectStore(RECONSTRUCTION_SESSIONS).put({ projectId, session }); await transactionComplete(transaction); } finally { db.close(); } }
  async deleteReconstructionSession(projectId: string): Promise<void> { assertProjectId(projectId); const db = await openDatabase(this.databaseName); try { const transaction = db.transaction(RECONSTRUCTION_SESSIONS, "readwrite"); transaction.objectStore(RECONSTRUCTION_SESSIONS).delete(projectId); await transactionComplete(transaction); } finally { db.close(); } }
}
export async function sha256Hex(data: ArrayBuffer): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", data); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function openDatabase(name: string): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(name, DATABASE_VERSION); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(ARTIFACTS)) db.createObjectStore(ARTIFACTS, { keyPath: "id" }); if (!db.objectStoreNames.contains(REVISIONS)) db.createObjectStore(REVISIONS, { keyPath: "projectId" }); if (!db.objectStoreNames.contains(RECONSTRUCTION_SESSIONS)) db.createObjectStore(RECONSTRUCTION_SESSIONS, { keyPath: "projectId" }); if (!db.objectStoreNames.contains(STUDIO_PROJECTS)) db.createObjectStore(STUDIO_PROJECTS, { keyPath: "id" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB open failed.")); }); }
function requestValue<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed.")); }); }
function transactionComplete(transaction: IDBTransaction): Promise<void> { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error ?? new Error("IndexedDB transaction failed.")); transaction.onabort = () => reject(transaction.error ?? new Error("IndexedDB transaction aborted.")); }); }
function validateArtifact(record: ArtifactRecord, data: ArrayBuffer): void { if (!record.id || record.id.length > 256) throw new Error("Invalid artifact ID."); if (!/^[a-f0-9]{64}$/.test(record.hash)) throw new Error("Artifact hash must be SHA-256 hex."); if (!Number.isSafeInteger(record.byteLength) || record.byteLength !== data.byteLength || record.byteLength < 0) throw new Error("Artifact byte length mismatch."); if (!record.mediaType || record.mediaType.length > 256 || !record.createdAt) throw new Error("Invalid artifact metadata."); }
function validateRevision(revision: ProjectRevision): void { if (!revision.projectId || revision.projectId.length > 256) throw new Error("Invalid project ID."); if (!Number.isSafeInteger(revision.revision) || revision.revision < 0) throw new Error("Invalid revision number."); if (!Number.isSafeInteger(revision.schemaVersion) || revision.schemaVersion <= 0) throw new Error("Invalid schema version."); if (revision.parentRevision !== undefined && (!Number.isSafeInteger(revision.parentRevision) || revision.parentRevision < 0)) throw new Error("Invalid parent revision."); if (new Set(revision.artifactIds).size !== revision.artifactIds.length) throw new Error("Duplicate artifact reference."); }
function validateProjectMetadata(project: StudioProjectRecord): void { if (!project.id || project.id.length > 256 || !project.name.trim() || project.name.length > 120) throw new Error("Invalid project metadata."); if (!Number.isFinite(Date.parse(project.createdAt)) || !Number.isFinite(Date.parse(project.updatedAt))) throw new Error("Invalid project timestamps."); if (new Set(project.assetIds).size !== project.assetIds.length) throw new Error("Duplicate project asset reference."); }
function assertProjectId(projectId: string): void { if (!projectId || projectId.length > 256) throw new Error("Invalid project ID."); }
