export function mountMarketingPage(root: HTMLElement): { dispose(): void } {
  root.innerHTML = `<div class="marketing-shell"><header class="marketing-header"><a class="marketing-brand" href="#top" aria-label="Veylune home"><span class="marketing-mark">V</span><span>veylune</span></a><button class="marketing-menu-toggle" type="button" aria-expanded="false" aria-controls="marketing-nav">Menu <span aria-hidden="true">＋</span></button><nav class="marketing-nav" id="marketing-nav" aria-label="Main navigation"><a href="#product">Product</a><a href="#workflow">Workflow</a><a href="#privacy">Privacy</a><a class="nav-studio-link" href="/studio#/overview">Studio <span aria-hidden="true">↗</span></a></nav></header>
    <main id="top"><section class="marketing-hero"><div class="hero-copy"><p class="marketing-eyebrow"><span class="eyebrow-dot"></span> A SPATIAL STUDIO FOR THE REAL WORLD</p><h1>Capture a place.<br><em>Keep its shape.</em></h1><p class="marketing-lede">Veylune turns a thoughtful walk around your subject into a spatial map you can refine and revisit—right on your device.</p><div class="marketing-actions"><a class="marketing-button button-light" href="/studio#/capture">Start a capture <span>↗</span></a><a class="marketing-text-link" href="#product">Explore the studio <span>↓</span></a></div><div class="hero-proof"><div class="proof-avatars" aria-hidden="true"><span>V</span><span>◎</span><span>⌁</span></div><p>Designed for considered, local-first capture</p></div></div><div class="hero-stage" aria-label="Animated visualization of a spatial scan"><div class="stage-glow"></div><div class="stage-grid"></div><div class="stage-ring ring-back"></div><div class="stage-ring ring-front"></div><div class="scan-sweep"></div><div class="stage-object"><div class="object-face face-front"></div><div class="object-face face-side"></div><div class="object-face face-top"></div><div class="object-wire"></div><span class="point-cloud point-one"></span><span class="point-cloud point-two"></span><span class="point-cloud point-three"></span><span class="point-cloud point-four"></span><span class="point-cloud point-five"></span><span class="point-cloud point-six"></span><span class="point-cloud point-seven"></span><span class="point-cloud point-eight"></span></div><div class="stage-label label-left"><span>01 / CAPTURE</span><b>Spatial map</b></div><div class="stage-label label-right"><span>REFINEMENT</span><b><i></i> Ready</b></div><div class="stage-axis axis-x">X <span>+ 02.481</span></div><div class="stage-axis axis-y">Y <span>− 11.203</span></div><div class="stage-coordinates">48° 51′ 24.1″ N <span>02° 21′ 08.2″ E</span></div></div><div class="hero-bottom-note"><span>01</span> &nbsp; MOVE THROUGH YOUR SUBJECT &nbsp; <span class="note-line"></span> &nbsp; SEE THE MAP TAKE SHAPE</div></section>
    <section class="trust-band" aria-label="Veylune principles"><div><span>01</span> LOCAL PROCESSING</div><i></i><div><span>02</span> CAMERA OR IMAGE SET</div><i></i><div><span>03</span> REFINEMENT AS YOU MOVE</div><i></i><div><span>04</span> YOUR FILES STAY YOURS</div></section>
    <section class="manifesto section-reveal" id="product"><div class="section-kicker"><span>THE VEYLUNE METHOD</span><span>01 — 03</span></div><div class="manifesto-grid"><h2>Spatial work<br>should feel <em>natural.</em></h2><div><p>Not a dashboard full of noise. A quiet, precise workspace that lets you focus on the subject, understand the scan, and keep your source material close.</p><a class="underlined-link" href="/studio#/overview">Step inside the studio <span>↗</span></a></div></div><div class="feature-grid"><article class="feature-card feature-card-wide"><div class="feature-visual capture-visual"><div class="capture-ring"></div><div class="capture-subject"><span></span><span></span><span></span></div><div class="capture-reticle">＋</div><div class="feature-chip">LIVE CAPTURE <i></i></div></div><div class="feature-meta"><span>01 / CAPTURE</span><span>CAMERA GUIDANCE</span></div><h3>Move with intention.</h3><p>Keep the camera steady, cover the subject from useful angles, and watch map refinement progress while you work.</p></article><article class="feature-card"><div class="feature-visual import-visual"><div class="import-stack"><i></i><i></i><i></i><i></i><b>＋</b></div><div class="import-path">/ LOCAL / PROJECT</div></div><div class="feature-meta"><span>02 / ORGANIZE</span><span>IMAGE SETS</span></div><h3>Bring your own frames.</h3><p>Start a local project from individual images or a folder of source photos.</p></article><article class="feature-card"><div class="feature-visual refine-visual"><div class="refine-rings"><i></i><i></i><i></i><b></b></div><div class="refine-tag">MAP  <strong>REFINING</strong></div></div><div class="feature-meta"><span>03 / REFINE</span><span>VISIBLE PROGRESS</span></div><h3>Know what’s happening.</h3><p>Follow iteration progress and cost signals, with clear recovery when a refinement needs another pass.</p></article></div></section>
    <section class="workflow-section section-reveal" id="workflow"><div class="workflow-heading"><div><p class="marketing-eyebrow">A CLEAR PATH THROUGH THE WORK</p><h2>From first frame<br>to <em>spatial context.</em></h2></div><p>Three deliberate steps. Your files and working map remain close at every stage.</p></div><div class="workflow-timeline"><article><span class="timeline-index">01</span><div class="timeline-icon icon-frame">⌗</div><p>01 — GATHER</p><h3>Choose a starting point.</h3><span>Open a camera capture, or organize a photo set into a new local project.</span></article><article><span class="timeline-index">02</span><div class="timeline-icon icon-scan">◉</div><p>02 — MOVE</p><h3>Cover the subject slowly.</h3><span>Use the capture guidance to collect keyframes from distinct viewpoints.</span></article><article><span class="timeline-index">03</span><div class="timeline-icon icon-map">⌁</div><p>03 — REFINE</p><h3>Review the evolving map.</h3><span>See the optimization state and keep your project ready for the next session.</span></article></div></section>
    <section class="privacy-section section-reveal" id="privacy"><div class="privacy-art"><div class="privacy-orbit orbit-a"></div><div class="privacy-orbit orbit-b"></div><div class="privacy-core">V</div><div class="privacy-lock">⌑</div><div class="privacy-data data-a">LOCAL STORAGE <b>ACTIVE</b></div><div class="privacy-data data-b">SOURCE FILES <b>ON DEVICE</b></div></div><div class="privacy-copy"><p class="marketing-eyebrow">PRIVATE BY DEFAULT</p><h2>Your source files<br>stay <em>with you.</em></h2><p>Images and project records are stored in this browser on your device. Veylune’s workspace is designed around local access and visible control.</p><a class="underlined-link" href="/studio#/import">Create a private project <span>↗</span></a></div></section>
    <section class="closing-section section-reveal"><div class="closing-orb"></div><p class="marketing-eyebrow">A MORE CONSIDERED WAY TO CAPTURE</p><h2>Look closer.<br><em>Keep more.</em></h2><a class="marketing-button button-light" href="/studio#/capture">Open Veylune Studio <span>↗</span></a><div class="closing-coordinate">VEYLUNE SPATIAL ENGINE &nbsp;·&nbsp; LOCAL BY DESIGN</div></section></main>
    <footer class="marketing-footer"><a class="marketing-brand" href="#top"><span class="marketing-mark">V</span><span>veylune</span></a><span>Spatial capture, made tangible.</span><a href="/studio#/overview">Go to Studio <span>↗</span></a><small>© 2026 VEYLUNE</small></footer></div>`;

  const menu = root.querySelector<HTMLButtonElement>(".marketing-menu-toggle")!;
  const nav = root.querySelector<HTMLElement>(".marketing-nav")!;
  const toggleMenu = (): void => {
    const isOpen = menu.getAttribute("aria-expanded") !== "true";
    menu.setAttribute("aria-expanded", String(isOpen));
    nav.classList.toggle("is-open", isOpen);
  };
  menu.addEventListener("click", toggleMenu);
  nav.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => {
    menu.setAttribute("aria-expanded", "false");
    nav.classList.remove("is-open");
  }));

  const reduceMotion = window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false;
  const revealElements = root.querySelectorAll<HTMLElement>(".section-reveal");
  if (!reduceMotion && "IntersectionObserver" in window) {
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); }
    }), { threshold: 0.14 });
    revealElements.forEach((element) => observer.observe(element));
  } else {
    revealElements.forEach((element) => element.classList.add("is-visible"));
  }
  return { dispose: () => { menu.removeEventListener("click", toggleMenu); } };
}
